// status: 'tengui' | 'falti' | 'pending'

var DATA = [
  {
    image: "ligaF22-23_normal.png",
    search: "aitana bonmati liga f 128",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "AitanaBonmatitoppsrookie15.jpg",
    search: "Aitana Bonmati topps rookie",
    status: 'falti',
    brilli: false,
  },
  {
    image: "154franceWomanWC.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "uefawomenoftheyear23.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "aitana-bonmati-f-stars-barcelona-322-liga-f-22-23.jpg",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "topss22-23.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "topss22-23-2.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "fc-barcelona-women-winners-2023-team-set-bonmati-numerada.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "topsnow3-22-32.png",
    search: "Aitana Bonmatí UWCL TOPPS NOW Card 3",
    status: 'falti',
    brilli: false,
  },
  {
    image: "wondergoal23-24wucl.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "duplamortal.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "2023-24 Topps - Champions League -021.jpg",
    search: "",
    status: 'tengui',
    brilli: true,
  },
  {
    image: "teamseasoncromotopps2.png",
    search: "",
    status: 'tengui',
    brilli: true,
  },
  {
    image: "toppssticker543.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "toppscromo27foil.png",
    search: "CROMO STICKER TOPPS 27 AITANA BONMATI",
    status: 'pending',
    brilli: true,
  },
  {
    image: "ligaFPremium.png",
    search: "",
    status: 'tengui',
    brilli: true,
  },
  {
    image: "ligaF2324.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "ligaf2324onfire.jpg",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "toppssimplicidad.png",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "430097317_tcimg_59D0C5C3.jpg",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "aitana-bonmati-barcelona-162-match-attax-extra-23-24.jpg",
    search: "",
    status: 'tengui',
    brilli: false,
  },
  {
    image: "aitana-bonmati-barcelona-crystal-parallel-162-match-attax-extra-23-24.jpg",
    search: "",
    status: 'tengui',
    brilli: true,
  },
  {
    image: "aitanaclub100.png",
    search: "",
    status: 'tengui',
    brilli: true,
  },
  {
    image: "aitanaFS12.png",
    search: "Aitana Bonmati Topps Future Stars",
    status: 'falti',
    brilli: false,
  },
  {
    image: "167eurocopa2022.png",
    search: "167 AITANA BONMATI ESPAÑA STICKER CROMO FUTBOL PANINI EUROCOPA FEMENINA 2022 EURO WOMEN WOMENS",
    status: 'falti',
    brilli: false,
  },
  {
    image: "512topps.png",
    search: "Topps UCC Living Set 512 Aitana Bonmatí",
    status: 'falti',
    brilli: false,
  },
  {
    image: "Aitana Bonmati Assist Queen topps.jpg",
    search: "Aitana Bonmati Assist Queen topps",
    status: 'falti',
    brilli: false,
  },
  {
    image: "Topps Simplicidad 2022 2023 22 23 Aitana Bonmati - FC Barcelona.png",
    search: "Topps Simplicidad 2022 2023 22 23 Aitana Bonmati - FC Barcelona",
    status: 'falti',
    brilli: false,
  },
  {
    image: "Aitana Bonmati Variation 2022-23 Topps Chrome Sapphire Women's UCL FC BARCELONA.png",
    search: "Aitana Bonmati Variation 2022-23 Topps Chrome Sapphire Women's UCL FC BARCELONA",
    status: 'falti',
    brilli: true,
  },
  {
    image: "fifa women's world cup 2023 23 panini aitana.png",
    search: "MUNDIAL FEMENINO AU NZ 2023 23 ACTUALIZACION ESPAÑA J6 J 6 AITANA BONMATI FIFA WOMEN'S AUSTRALIA",
    status: 'falti',
    brilli: false,
  },
  {
    image: "toppschrome.png",
    search: "FC Barcelona Femenino Topps Chrome Women 2022-2023 22 23 14 Aitana Bonmati - FC Barcelona",
    status: 'falti',
    brilli: false,
  },
  {
    image: "cm5.png",
    search: "Aitana Bonmatí. Cm-5. Topps",
    status: 'falti',
    brilli: true,
  },
  {
    image: "toppsdeco.png",
    search: "Topps DECO UCC 2023 2024 23 24 - Aitana Bonmati - FC Barcelona",
    status: 'falti',
    brilli: false,
  },
  {
    image: "putaespanya.png",
    search: "#53 AITANA BONMATI PANINI CARREFOUR ¡VAMOS SELECCION! ESPAÑA",
    status: 'pending',
    brilli: false,
  },
  {
    image: "toppsmerlinviejo.png",
    search: "TOPPS MERLIN HERITAGE 2023 2024 23 24 Carta - 70 Aitana Bonmati Barcelona",
    status: 'falti',
    brilli: false,
  },
];
